select_origin: directory
files_origin: "C:\\Users\\chauv\\Documents\\BIBLIO-OALEX\\out"
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ""
history: true
focus_max: 2
record_types:
  undefined:
    fill: "#858585"
    stroke: "#858585"
  AUTHOR:
    fill: "#0000ff"
    stroke: "#0000ff"
  WORK:
    fill: "#8EF3FB"    
    stroke: "#8EF3FB"    
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
  works:
    stroke: simple
    color: "#0000cd"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 5
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 2
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
chronological_record_meta: created
record_metas: []
title: "Author"
author: "jmc"
description: "Open Alex node for authors"
keywords: []
link_symbol: ""
csl: ""
bibliography: ""
csl_locale: ""
css_custom: ""
devtools: false
lang: en
name: ""
